### ISSUE TITLE
IO Redirection test passes locally but fails on github

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#104]
The text-ui-test passes locally on my computer
![image](https://user-images.githubusercontent.com/49228945/78998049-604b5e00-7b7a-11ea-9194-d8f59488d6f4.png)
but it fails when pulling request
![image](https://user-images.githubusercontent.com/49228945/78998071-6f321080-7b7a-11ea-8d29-04d79b968f27.png)
Wonder how I can fix it?

**Comment by MeLoveCarbs** [comment]
Hi, I've encountered this issue too. It could be caused by an old jar file in your local build/lib directory, resulting in a false positive test pass. Try deleting the old jar and making a new jar via gradle shadowJar, after which your local test would be similar to the CI tool and you can fix accordingly.

**Comment by SibingWu** [comment]
> Hi, I've encountered this issue too. It could be caused by an old jar file in your local build/lib directory, resulting in a false positive test pass. Try deleting the old jar and making a new jar via gradle shadowJar, after which your local test would be similar to the CI tool and you can fix accordingly.

thx!
