### ISSUE TITLE
Are we supposed to add JavaDoc comments in tP v1.0?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#56]
I'm not sure whether we are supposed to add JavaDoc comments in tP v1.0, but when we do not add the JavaDoc comments, the Java CI tests fail?

**Comment by JeremyTakigawa** [comment]
Well it's always a good habit to have JavaDoc especially when you are working as a team

**Comment by damithc** [comment]
> I'm not sure whether we are supposed to add JavaDoc comments in tP v1.0, but when we do not add the JavaDoc comments, the Java CI tests fail?

The code is expected to be _well-documented_, which includes using javadoc comments appropriately.

Having said that, you can modify the checkstyle config file to allow methods without javadoc comments as the given coding standard does not specifically disallow methods/classes without javadoc comments. I'll look into removing that rule from the checkstyle config so that it will not be enforced against your PRs in https://github.com/nus-cs2113-AY1920S2/tp/pulls

**Comment by Zhilin-Huang** [comment]
> > I'm not sure whether we are supposed to add JavaDoc comments in tP v1.0, but when we do not add the JavaDoc comments, the Java CI tests fail?
> 
> The code is expected to be _well-documented_, which includes using javadoc comments appropriately.
> 
> Having said that, you can modify the checkstyle config file to allow methods without javadoc comments as the given coding standard does not specifically disallow methods/classes without javadoc comments. I'll look into removing that rule from the checkstyle config so that it will not be enforced against your PRs in https://github.com/nus-cs2113-AY1920S2/tp/pulls

Thanks for the clarification!
