### ISSUE TITLE
JUnitest on "void" return function

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#64]
Given than we can have JUnitest for those functions that return something, I wonder if we can test for functions such as "execute" which return "void"?

**Comment by damithc** [comment]
Testing is essentially ensuring that the actual behavior is same as the expected behavior. If the return value of a method is not able to tell you the actual behavior, you can try some other ways to verify it.

For example, if the execute method is supposed to add an object to a list, you can check the last element in the list to confirm that the object has been added there as expected.

If the actual behavior is hard to verify (e.g., the method simply prints something), that means the _testability_ of the method is low -- you can try to redesign the method to improve the testability e.g, get the method to return the string instead of printing it directly.

**Comment by SibingWu** [comment]
> Testing is essentially ensuring that the actual behavior is same as the expected behavior. If the return value of a method is not able to tell you the actual behavior, you can try some other ways to verify it.
> 
> For example, if the execute method is supposed to add an object to a list, you can check the last element in the list to confirm that the object has been added there as expected.
> 
> If the actual behavior is hard to verify (e.g., the method simply prints something), that means the _testability_ of the method is low -- you can try to redesign the method to improve the testability e.g, get the method to return the string instead of printing it directly.

So it means that, when doing JUnitest for adding something to the list, the thing used for test is truely added into the list, and we need to remove it after test finishes?

**Comment by damithc** [comment]
> So it means that, when doing JUnitest for adding something to the list, the thing used for test is truely added into the list, and we need to remove it after test finishes?

Yes, _if_ that addition could affect the result of other tests.

**Comment by SibingWu** [comment]
> So it means that, when doing JUnitest for adding something to the list, the thing used for test is truely added into the list, and we need to remove it after test finishes?
> 
> Yes, if that addition could affect the result of other tests.

Thx Prof!
